name: Helm Chart Tagger

on:
    repository_dispatch:
        types: [helm_chart_image_tag_update]
    workflow_dispatch:
        inputs:
            release_tag:
                description: Image tag to update values.yaml file
                type: string
                required: true
            release_id:
                description: Unique ARM release ID for the deployment
                type: string
                required: true
            release_note:
                description: 'Confluence link to release notes'
                type: string
                required: true
                
permissions:
  contents: write
  pull-requests: write

jobs:
    update-helm-chart:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6
              with:
                persist-credentials: false

            - name: Update image tag
              run: |
                sed -i -E "/image/{n;s~(tag: ).*~\1\"${{github.event.client_payload.release_tag}}\"~}" values.yaml
                sed -i '/^metadata:/,/^[^ ]/ s/^\(\s*release\.tag:\s*\).*/\1"${{github.event.client_payload.release_tag}}"/' application.yaml
                git diff
            
            - name: Clean git auth headers
              run: |
                git config --global --remove-section http.https://github.com || true
                git config --global --unset-all http.https://github.com/.extraheader || true

            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v6
              with:
                  delete-branch: true
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: |
                    Prod deployment for release version ${{ github.event.client_payload.release_tag }}
                    ARM-Release-ID: ${{ github.event.client_payload.release_id }}
                  title: '🏷️ PROD RELEASE: Bump image version to ${{ github.event.client_payload.release_tag }}'
                  author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
                  branch: 'auto-pr-branch-${{ github.event.client_payload.release_tag }}'
                  base: main
                  body: |
                       AUTO GENERATED PR:
                        ARM Release ID: ${{ github.event.client_payload.release_id }}
                        Release Version: ${{ github.event.client_payload.release_tag }} 
                        Release Note: ${{ github.event.client_payload.release_note }}
                  labels: |
                    automated pr

            - name: Enable Pull Request Automerge
              run: gh pr merge --merge --auto "${{ steps.cpr.outputs.pull-request-number }}"
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
            # - name: Start release
            #   run: |
            #     response=$(curl -X POST \
            #         -H "Content-Type: application/json" \
            #         https://yfoa5flvfk.execute-api.us-east-1.amazonaws.com/staging/start-release \
            #         -d '{
            #             "repo": "${{ github.event.repository.full_name }}",
            #             "sha": "${{ steps.cpr.outputs.pull-request-head-sha }}",
            #             "release_id": "${{ github.event.client_payload.release_tag }}"
            #         }')
            #         echo "Response: $response"
            #         status=$(echo "$response" | jq -r '.status')
            #         if [ "$status" -ne 200 ]; then
            #           echo "Error: API call failed with status $status"
            #           exit 1
            #         fi

            - name: Get ARM Access Token
              run: |
                RESPONSE=$(curl -s -X POST \
                  "${{secrets.ARM_COGNITO_ENDPOINT}}" \
                  -H "Content-Type: application/x-www-form-urlencoded" \
                  -u "${{ secrets.ARM_COGNITO_CLIENTID }}:${{ secrets.ARM_COGNITO_CLIENTSECRET }}" \
                  --data-urlencode "grant_type=client_credentials" \
                  --data-urlencode "scope=bridge-api/arm-request-approval")

                TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')

                if [ "$TOKEN" = "null" ] || [ -z "$TOKEN" ]; then
                  echo "Failed to obtain access token"
                  echo "$RESPONSE"
                  exit 1
                fi
                echo "ARM_TOKEN=$TOKEN" >> $GITHUB_ENV

            - name: Request ARM Approval
              run: |
                RESPONSE=$(curl -X POST \
                    "${{secrets.ARM_HOST}}/prod/arm/request/approval" \
                    -H "Authorization: Bearer $ARM_TOKEN" \
                    -H "Content-Type: application/json" \
                    -d '{
                      "release_id": "${{github.event.client_payload.release_id}}",
                      "deployment_context": {
                        "artifact": {
                          "type": "docker",
                          "name": "glow-portals:${{github.event.client_payload.release_tag}}",
                          "version": "${{github.event.client_payload.release_tag}}",
                          "artifact_uri": "http://dockerhub.com/artifactory/"
                        },
                        "execution_context": {
                          "commit_sha": "${{ steps.cpr.outputs.pull-request-head-sha }}",
                          "pull_request_number": "${{ steps.cpr.outputs.pull-request-number }}",
                          "tag": "${{github.event.client_payload.release_tag}}",
                          "author": "${{github.actor}}",
                          "commit_message": "Prod deployment for release version ${{ github.event.client_payload.release_tag }}"
                        }
                      }
                    }')
        
                    echo "Response: $RESPONSE"
                    status=$(echo "$RESPONSE" | jq -r '.status')
                    if [ "$status" -ne 200 ]; then
                      echo "Error: Request ARM approval API call failed with status $status"
                      exit 1
                    fi
            

    # port-logs:
    #     if: success() || failure()
    #     needs: [ update-helm-chart ]
    #     uses: vkirankumar/portal-glow-mock/.github/workflows/post-logs-to-elastic.yaml@main
    #     with:
    #         release_tag: ${{github.event.client_payload.release_tag}}
    #     secrets:
    #         ELASTIC_HOST: ${{ secrets.ELASTIC_HOST }}
    #         ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}

    # notify-job-status:
    #     if: success() || failure()
    #     uses: vkirankumar/portal-glow-mock/.github/workflows/notify-events.yaml@main
    #     needs: [ update-helm-chart, port-logs ]
    #     with:
    #         release_tag: ${{github.event.client_payload.release_tag}}
    #         notfication_summary: "[CREATE-HELM-PR] React Portals <b>PROD</b> deployment"
    #     secrets:
    #         TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
